# Definitions 

DATA_FONT_SIZE = 18
DATA_FONT_COLOR =  (40,40,40)

MUTATION_WEIGHT_MODIFY_CHANCE = 0.5
MUTATION_ARRAY_MIX_PERC = 0.5
MUTATION_CUT_OFF = 0.4
MUTATION_BAD_TO_KEEP = 0.2
MUTATION_MODIFY_CHANCE_LIMIT = 0.9

MOVE_UP_CHANCE = 0.5


NNET_INPUTS = 2
NNET_HIDDEN = 5
NNET_OUTPUTS = 3



MUTATION_BAD_TO_KEEP = 0.2
MUTATION_MODIFY_CHANCE_LIMIT = 0.4